target = "my-image-model"
api_key = "<token>"
url = "<url>"
model_type = "image"
dataset = "mnist"
labels="""
{
  "0": "0",
  "1": "1",
  "2": "2",
  "3": "3",
  "4": "4",
  "5": "5",
  "6": "6",
  "7": "7",
  "8": "8",
  "9": "9"
}
"""